/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "srvdns.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Resultado *
inicializar_srvdns_1(datini *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, inicializar_srvdns,
		(xdrproc_t) xdr_datini, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
consulta_record_1(paramconsulta *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consulta_record,
		(xdrproc_t) xdr_paramconsulta, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_total_dominio_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_total_dominio,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_total_registro_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_total_registro,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_total_dominioregistro_1(domrecord *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_total_dominioregistro,
		(xdrproc_t) xdr_domrecord, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_num_dominios_1(void *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_num_dominios,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_num_records_1(void *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_num_records,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_nombre_dominio_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_nombre_dominio,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Resultado *
obtener_nombre_record_1(int *argp, CLIENT *clnt)
{
	static Resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, obtener_nombre_record,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_Resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
