/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SRVDNS_H_RPCGEN
#define _SRVDNS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define LENMSG 1024

typedef char *cadena;

struct Lista {
	cadena dato;
	struct Lista *siguiente;
};
typedef struct Lista Lista;

struct datini {
	Lista *nomdominios;
	Lista *nomtiporecords;
};
typedef struct datini datini;

struct paramconsulta {
	cadena nomdominio;
	cadena tiporecord;
	cadena clave;
};
typedef struct paramconsulta paramconsulta;

struct domrecord {
	int ndxdom;
	int ndxrecord;
};
typedef struct domrecord domrecord;

struct Resultado {
	int caso;
	union {
		cadena msg;
		int val;
		cadena err;
	} Resultado_u;
};
typedef struct Resultado Resultado;

#define SRVDNS 0x2023f001
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define inicializar_srvdns 1
extern  Resultado * inicializar_srvdns_1(datini *, CLIENT *);
extern  Resultado * inicializar_srvdns_1_svc(datini *, struct svc_req *);
#define consulta_record 2
extern  Resultado * consulta_record_1(paramconsulta *, CLIENT *);
extern  Resultado * consulta_record_1_svc(paramconsulta *, struct svc_req *);
#define obtener_total_dominio 3
extern  Resultado * obtener_total_dominio_1(int *, CLIENT *);
extern  Resultado * obtener_total_dominio_1_svc(int *, struct svc_req *);
#define obtener_total_registro 4
extern  Resultado * obtener_total_registro_1(int *, CLIENT *);
extern  Resultado * obtener_total_registro_1_svc(int *, struct svc_req *);
#define obtener_total_dominioregistro 5
extern  Resultado * obtener_total_dominioregistro_1(domrecord *, CLIENT *);
extern  Resultado * obtener_total_dominioregistro_1_svc(domrecord *, struct svc_req *);
#define obtener_num_dominios 6
extern  Resultado * obtener_num_dominios_1(void *, CLIENT *);
extern  Resultado * obtener_num_dominios_1_svc(void *, struct svc_req *);
#define obtener_num_records 7
extern  Resultado * obtener_num_records_1(void *, CLIENT *);
extern  Resultado * obtener_num_records_1_svc(void *, struct svc_req *);
#define obtener_nombre_dominio 8
extern  Resultado * obtener_nombre_dominio_1(int *, CLIENT *);
extern  Resultado * obtener_nombre_dominio_1_svc(int *, struct svc_req *);
#define obtener_nombre_record 9
extern  Resultado * obtener_nombre_record_1(int *, CLIENT *);
extern  Resultado * obtener_nombre_record_1_svc(int *, struct svc_req *);
extern int srvdns_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define inicializar_srvdns 1
extern  Resultado * inicializar_srvdns_1();
extern  Resultado * inicializar_srvdns_1_svc();
#define consulta_record 2
extern  Resultado * consulta_record_1();
extern  Resultado * consulta_record_1_svc();
#define obtener_total_dominio 3
extern  Resultado * obtener_total_dominio_1();
extern  Resultado * obtener_total_dominio_1_svc();
#define obtener_total_registro 4
extern  Resultado * obtener_total_registro_1();
extern  Resultado * obtener_total_registro_1_svc();
#define obtener_total_dominioregistro 5
extern  Resultado * obtener_total_dominioregistro_1();
extern  Resultado * obtener_total_dominioregistro_1_svc();
#define obtener_num_dominios 6
extern  Resultado * obtener_num_dominios_1();
extern  Resultado * obtener_num_dominios_1_svc();
#define obtener_num_records 7
extern  Resultado * obtener_num_records_1();
extern  Resultado * obtener_num_records_1_svc();
#define obtener_nombre_dominio 8
extern  Resultado * obtener_nombre_dominio_1();
extern  Resultado * obtener_nombre_dominio_1_svc();
#define obtener_nombre_record 9
extern  Resultado * obtener_nombre_record_1();
extern  Resultado * obtener_nombre_record_1_svc();
extern int srvdns_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_cadena (XDR *, cadena*);
extern  bool_t xdr_Lista (XDR *, Lista*);
extern  bool_t xdr_datini (XDR *, datini*);
extern  bool_t xdr_paramconsulta (XDR *, paramconsulta*);
extern  bool_t xdr_domrecord (XDR *, domrecord*);
extern  bool_t xdr_Resultado (XDR *, Resultado*);

#else /* K&R C */
extern bool_t xdr_cadena ();
extern bool_t xdr_Lista ();
extern bool_t xdr_datini ();
extern bool_t xdr_paramconsulta ();
extern bool_t xdr_domrecord ();
extern bool_t xdr_Resultado ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SRVDNS_H_RPCGEN */
