/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "srvdns.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
srvdns_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datini inicializar_srvdns_1_arg;
		paramconsulta consulta_record_1_arg;
		int obtener_total_dominio_1_arg;
		int obtener_total_registro_1_arg;
		domrecord obtener_total_dominioregistro_1_arg;
		int obtener_nombre_dominio_1_arg;
		int obtener_nombre_record_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case inicializar_srvdns:
		_xdr_argument = (xdrproc_t) xdr_datini;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) inicializar_srvdns_1_svc;
		break;

	case consulta_record:
		_xdr_argument = (xdrproc_t) xdr_paramconsulta;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) consulta_record_1_svc;
		break;

	case obtener_total_dominio:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_total_dominio_1_svc;
		break;

	case obtener_total_registro:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_total_registro_1_svc;
		break;

	case obtener_total_dominioregistro:
		_xdr_argument = (xdrproc_t) xdr_domrecord;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_total_dominioregistro_1_svc;
		break;

	case obtener_num_dominios:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_num_dominios_1_svc;
		break;

	case obtener_num_records:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_num_records_1_svc;
		break;

	case obtener_nombre_dominio:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_nombre_dominio_1_svc;
		break;

	case obtener_nombre_record:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Resultado;
		local = (char *(*)(char *, struct svc_req *)) obtener_nombre_record_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SRVDNS, PRIMERA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SRVDNS, PRIMERA, srvdns_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SRVDNS, PRIMERA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SRVDNS, PRIMERA, srvdns_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SRVDNS, PRIMERA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
