/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "srvdns.h"

bool_t
xdr_cadena (XDR *xdrs, cadena *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, LENMSG))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Lista (XDR *xdrs, Lista *objp)
{
	register int32_t *buf;

	 if (!xdr_cadena (xdrs, &objp->dato))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->siguiente, sizeof (Lista), (xdrproc_t) xdr_Lista))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datini (XDR *xdrs, datini *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->nomdominios, sizeof (Lista), (xdrproc_t) xdr_Lista))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nomtiporecords, sizeof (Lista), (xdrproc_t) xdr_Lista))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_paramconsulta (XDR *xdrs, paramconsulta *objp)
{
	register int32_t *buf;

	 if (!xdr_cadena (xdrs, &objp->nomdominio))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->tiporecord))
		 return FALSE;
	 if (!xdr_cadena (xdrs, &objp->clave))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_domrecord (XDR *xdrs, domrecord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ndxdom))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ndxrecord))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Resultado (XDR *xdrs, Resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->caso))
		 return FALSE;
	switch (objp->caso) {
	case 0:
		 if (!xdr_cadena (xdrs, &objp->Resultado_u.msg))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_int (xdrs, &objp->Resultado_u.val))
			 return FALSE;
		break;
	case 2:
		 if (!xdr_cadena (xdrs, &objp->Resultado_u.err))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
